version: "3"
volumes:
  bundle:
  postgres:
services:
  redis:
    image: redis:4.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./tmp/data/redis:/data:cached
  db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  app:
    build:
      context: .
    stdin_open: true
    tty: true
    command: bin/rails s -p 3000 -b '0.0.0.0'
    volumes:
      - bundle:/usr/local/bundle
      - .:/usr/src/app:delegated
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - db
